# Generated by Django 4.0.2 on 2022-03-08 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Нэвтрэх нэр')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Овог')),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M'), ('FI', 'FI'), ('MI', 'MI'), ('U', 'U'), ('X', 'X')], max_length=2, null=True, verbose_name='Хүйс')),
                ('profile_picture', models.CharField(max_length=200, null=True, verbose_name='Зураг')),
                ('birthday', models.DateField(null=True, verbose_name='Төрсөн өдөр')),
                ('dial_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Утасны код')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Утасны дугаар')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='И-мэйл хаяг')),
                ('fb_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook user id')),
                ('google_user_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='google user id')),
                ('apple_user_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='apple user id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй эсэх')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Ажилтан эсэх')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Хэрэглэгч',
                'verbose_name_plural': 'Хэрэглэгчид',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Role-ийн нэр')),
                ('code', models.CharField(max_length=200, verbose_name='Role-ийн код')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('dial_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Утасны код')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Утасны дугаар')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='И-мэйл хаяг')),
                ('code', models.CharField(max_length=6, verbose_name='Баталгаажуулах код')),
                ('send_sms_time', models.DateTimeField()),
                ('is_verify', models.BooleanField(default=False)),
                ('try_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Оролдсон тоо')),
            ],
            options={
                'verbose_name': 'Баталгаажуулах код',
                'verbose_name_plural': 'Баталгаажуулах кодууд',
                'db_table': 'notify_verification_codes',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_ip', models.CharField(max_length=16, verbose_name='Төхөөрөмжийн IP хаяг')),
                ('device_name', models.CharField(max_length=200, verbose_name='Төхөөрөмжийн нэр')),
                ('device_os', models.CharField(max_length=200, verbose_name='Төхөөрөмжийн үйлдэлийн систем')),
                ('device_based_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Төхөөрөмжөөр үүсгэсэн токен')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_settings_user', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Холбогдсон төхөөрөмж',
                'verbose_name_plural': 'Холбогдсон төхөөрөмжүүд',
                'db_table': 'devices_connected',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.rolemodel', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
