# Generated by Django 3.2.12 on 2022-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bank',
            field=models.CharField(choices=[('KHAN', 'Хаан банк'), ('GOLOMT', 'Голомт банк'), ('STATE', 'Төрийн банк')], default='KHAN', max_length=10, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Данс нэр'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Данс дугаар'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='home_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Гэрийн хаяг'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id_front',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Иргэний үнэмлэх урд тал'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id_rear',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Иргэний үнэмлэх ард тал'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оноо'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='selfie',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Зураг'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='signature',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Гарын үсэг'),
        ),
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='send_sms_time',
            field=models.DateTimeField(verbose_name='sms илгээсэн хугацаа'),
        ),
    ]
