# Generated by Django 3.2 on 2022-10-26 00:04

from django.db import migrations, models
import django.db.models.deletion
import uo_core.utills


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=uo_core.utills.PathAndRename('user_pics/'), verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='account.rolemodel', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='send_sms_time',
            field=models.DateTimeField(verbose_name='sms илгээсэн хугацаа'),
        ),
    ]
