# Generated by Django 3.2 on 2023-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221026_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='verify_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='verify code'),
        ),
    ]
