# Generated by Django 3.2.12 on 2022-04-25 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220425_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оноо'),
        ),
    ]
