# Generated by Django 3.2 on 2022-09-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220425_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='id_rear',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='point',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='selfie',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='signature',
        ),
    ]
