# Generated by Django 3.2 on 2022-10-19 18:45

from django.db import migrations, models
import uo_core.utills


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=uo_core.utills.PathAndRename('user_pics/'), verbose_name='Зураг'),
        ),
    ]
