from django.utils.translation import gettext as _

USER_FIND_ERROR = _("Хэрэглэгч олдсонгүй")
CREATE_ERROR = _("Хадгалах үйлдэлд алдаа гарлаа")
NOT_CHANGE_ERROR = _("Өөрчлөгдөөгүй байна")
TOKEN_EXPIRED_ERROR = _("Токений хугацаа дууссан")
USER_NOT_ACCESS = _("Хандах эрх хүрэхгүй байна.")

ACCOUNT_WRONG_PASSWORD = _("Хэрэглэгчийн нэвтрэх нэр, нууц үг буруу байна.")
ACCOUNT_CANNOT_LOGIN = _("Нэвтрэх боломжгүй хэрэглэгч.")
ACCOUNT_WRONG_REPEAT_PASSWORD = _("Давтаж оруулсан нууц үг буруу байна.")
ACCOUNT_SAME_PASSWORD_ERROR = _("Өмнөх нууц үгээс өөр нууц үг оруулна уу!")
ACCOUNT_VALID_PASSWORD_ERROR = _("Нууц үг тэнцсэнгүй, өөр нууц үг оруулна уу!")
ACCOUNT_PASSWORD_NOT_FILLED = _("Нууц үгээ оруулна уу!")
ACCOUNT_VERIFY_CODE_ERROR = _("Код баталгаажуулахад алдаа гарлаа.")
ACCOUNT_WRONG_VERIFICATION_CODE = _("Таны оруулсан код буруу байна.")
ACCOUNT_VERIFICATION_CODE_BLOCKED = _("Таны өдрийн хязгаарт хүрсэн байна")
ACCOUNT_INVALID_PHONE = _("Та утасны дугаараа зөв оруулна уу!")
ACCOUNT_BLOCKED = _("Таны эрх хаагдсан байна. Та нууц үгээ сэргээнэ үү!")
ACCOUNT_INVALID_EMAIL = _("Та и-мэйл хаягаа зөв оруулна уу!!")
ACCOUNT_EMAIL_VERIFICATION_CODE = _("Таны баталгаажуулах код")
ACCOUNT_EMAIL_VERIFICATION_CODE_ERROR = _("Таны баталгаажуулах код буруу байна")
ACCOUNT_VERIFY_YOUR_EMAIL = _("Та и-мэйл-ээ баталгаажуулна уу.")
ACCOUNT_SENT_ALREADY = _("Таны и-мэйл-рү баталгаажуулалт илгээгдсэн байна.")
ACCOUNT_WRONG_OLD_PASSWORD = _("Хуучин нууц үг буруу байна.")
ACCOUNT_REGISTER_USER = _("Та амжилттай бүртгэгдлээ.")