# Generated by Django 3.2.12 on 2022-09-20 16:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20220425_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('firstname', models.CharField(max_length=100, unique=True, verbose_name='Нэр')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Овог')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дууддаг нэр')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Нас')),
                ('level', models.TextField(blank=True, null=True, verbose_name='Спорт Зэрэг')),
            ],
            options={
                'verbose_name': 'Багш',
                'verbose_name_plural': 'Багшнууд',
                'db_table': 'surgalt_teachers',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Нэр')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Sunday'), (7, 'Saturday')], max_length=13)),
                ('time', models.DateTimeField(verbose_name='Цаг')),
                ('type', models.CharField(max_length=100, verbose_name='Төрөл')),
                ('max_student_cnt', models.IntegerField(verbose_name='Хэдэн сурагч суралцах боломжтой')),
                ('current_student_cnt', models.IntegerField(verbose_name='Одоо суралцаж байгаа сурагч')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.rolemodel', verbose_name='role')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.teachermodel', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Сургалт',
                'verbose_name_plural': 'Сургалтууд',
                'db_table': 'surgalt_course',
            },
        ),
    ]
