# Generated by Django 3.2 on 2022-10-26 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surgalt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequestmodel',
            name='student',
        ),
        migrations.AddField(
            model_name='courserequestmodel',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Төрсөн өдөр'),
        ),
        migrations.AddField(
            model_name='courserequestmodel',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Бүртгүүлэгч'),
        ),
        migrations.AddField(
            model_name='courserequestmodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='courserequestmodel',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('FI', 'FI'), ('MI', 'MI'), ('U', 'U'), ('X', 'X')], max_length=2, null=True, verbose_name='Хүйс'),
        ),
        migrations.AddField(
            model_name='courserequestmodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Овог'),
        ),
        migrations.AddField(
            model_name='coursestudentmodel',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Төрсөн өдөр'),
        ),
        migrations.AddField(
            model_name='coursestudentmodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='coursestudentmodel',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('FI', 'FI'), ('MI', 'MI'), ('U', 'U'), ('X', 'X')], max_length=2, null=True, verbose_name='Хүйс'),
        ),
        migrations.AddField(
            model_name='coursestudentmodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Овог'),
        ),
        migrations.AlterField(
            model_name='studenttimetablemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursestudentmodel', verbose_name='Суралцагч'),
        ),
    ]
