# Generated by Django 3.2.12 on 2022-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='time',
            field=models.TimeField(verbose_name='Цаг'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='type',
            field=models.CharField(choices=[('A', 'Насанд хүрэгчид'), ('C', 'Хүүхэд'), ('S', 'Оюутан'), ('O', 'Ахмад настан')], max_length=100, verbose_name='Төрөл'),
        ),
    ]
