# Generated by Django 3.2 on 2022-11-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0003_auto_20221102_1540'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courserequestmodel',
            constraint=models.UniqueConstraint(fields=('course', 'first_name', 'last_name', 'gender', 'birthday', 'start_date'), name='surgalt_courserequestmodel_unique'),
        ),
    ]
