# Generated by Django 3.2 on 2022-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0003_auto_20220922_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Намтар'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Спорт Зэрэг'),
        ),
    ]
