# Generated by Django 3.2 on 2022-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0004_courserequestmodel_surgalt_courserequestmodel_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudentmodel',
            old_name='student',
            new_name='created_user',
        ),
        migrations.AlterField(
            model_name='courserequestmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Хүсэлт илгээсэн'), (2, 'Төлбөр хүлээгдэж байгаа'), (3, 'Бусад'), (4, 'Батлагдсан')], default=1, verbose_name='Төлөв'),
        ),
    ]
