# Generated by Django 3.2 on 2022-09-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0004_auto_20220922_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='level',
            field=models.CharField(choices=[('ouhm', 'Олон улс хэмжээний мастер (ОУХМ)'), ('sm', 'Спортын Мастер (СМ)'), ('dm', 'Спортын Мастер (ДМ)'), ('level1', '1-р зэрэг'), ('level2', '2-р зэрэг'), ('level3', '3-р зэрэг'), ('nolevel', '')], default='nolevel', max_length=100, verbose_name='Спорт Зэрэг'),
        ),
    ]
