# Generated by Django 3.2 on 2022-10-09 01:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surgalt', '0005_alter_teachermodel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTimeTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_date', models.DateField(default=datetime.date.today, verbose_name='Сургалт орсон өдөр')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Анги - Ирц',
                'verbose_name_plural': 'Анги - Ирц',
                'db_table': 'surgalt_course_time_table',
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Нээлттэй эсэх'),
        ),
        migrations.CreateModel(
            name='StudentTimeTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('attendance', models.BooleanField(default=True, verbose_name='Ирсэн')),
                ('course_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursetimetablemodel', verbose_name='Хичээл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Суралцагч')),
            ],
            options={
                'verbose_name': 'Сурагч - Ирц',
                'verbose_name_plural': 'Сурагч - Ирц',
                'db_table': 'surgalt_student_time_table',
            },
        ),
        migrations.AddField(
            model_name='coursetimetablemodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursemodel', verbose_name='Анги'),
        ),
        migrations.CreateModel(
            name='CourseStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Эхлэх өдөр')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дуусах өдөр')),
                ('active', models.BooleanField(default=True, verbose_name='Идвэхтэй')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Төлбөр төлсөн өдөр')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursemodel', verbose_name='Анги')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Суралцагч')),
            ],
            options={
                'verbose_name': 'Анги - Сурагч',
                'verbose_name_plural': 'Анги - Сурагч',
                'db_table': 'surgalt_course_student',
            },
        ),
        migrations.CreateModel(
            name='CourseRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Хүсэлт илгээсэн'), (2, 'Төлбөр хүлээгдэж байгаа'), (3, 'Бусад'), (3, 'Батлагдсан')], verbose_name='Төлөв')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Эхлэх өдөр')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дуусах өдөр')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Төлбөр төлсөн өдөр')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursemodel', verbose_name='Анги')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Суралцагч')),
            ],
            options={
                'verbose_name': 'Анги - Бүртгэл',
                'verbose_name_plural': 'Анги - Бүртгэл',
                'db_table': 'surgalt_course_request',
            },
        ),
    ]
