# Generated by Django 3.2 on 2023-01-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0006_alter_coursestudentmodel_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Бичлэг линк')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='Тайлбар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='surgalt.coursestudentmodel', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Суралцагчийн бичлэг',
                'verbose_name_plural': 'Суралцагчийн бичлэгнүүд',
                'db_table': 'surgalt_course_student_videos',
            },
        ),
    ]
