# Generated by Django 3.2 on 2022-10-09 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surgalt', '0006_auto_20221009_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('test_date', models.DateField(default=datetime.date.today, verbose_name='Сургалт орсон өдөр')),
                ('r1', models.IntegerField(choices=[(1, 'Нэг'), (2, 'Хоёр'), (3, 'Гурав'), (4, 'Дөрөв'), (5, 'Тав'), (6, 'Зургаа'), (7, 'Долоо'), (8, 'Найм'), (9, 'Ес'), (10, 'Арав')], default=5, verbose_name='Таталт')),
                ('r2', models.IntegerField(choices=[(1, 'Нэг'), (2, 'Хоёр'), (3, 'Гурав'), (4, 'Дөрөв'), (5, 'Тав'), (6, 'Зургаа'), (7, 'Долоо'), (8, 'Найм'), (9, 'Ес'), (10, 'Арав')], default=5, verbose_name='Тулгалт')),
                ('r3', models.IntegerField(choices=[(1, 'Нэг'), (2, 'Хоёр'), (3, 'Гурав'), (4, 'Дөрөв'), (5, 'Тав'), (6, 'Зургаа'), (7, 'Долоо'), (8, 'Найм'), (9, 'Ес'), (10, 'Арав')], default=5, verbose_name='Топс')),
                ('r4', models.IntegerField(choices=[(1, 'Нэг'), (2, 'Хоёр'), (3, 'Гурав'), (4, 'Дөрөв'), (5, 'Тав'), (6, 'Зургаа'), (7, 'Долоо'), (8, 'Найм'), (9, 'Ес'), (10, 'Арав')], default=5, verbose_name='Подача')),
                ('r5', models.IntegerField(choices=[(1, 'Нэг'), (2, 'Хоёр'), (3, 'Гурав'), (4, 'Дөрөв'), (5, 'Тав'), (6, 'Зургаа'), (7, 'Долоо'), (8, 'Найм'), (9, 'Ес'), (10, 'Арав')], default=5, verbose_name='Ивэлт')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgalt.coursemodel', verbose_name='Анги')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Суралцагч')),
            ],
            options={
                'verbose_name': 'Анги - Тест',
                'verbose_name_plural': 'Анги - Тест',
                'db_table': 'surgalt_student_test',
            },
        ),
    ]
