# Generated by Django 3.2 on 2022-10-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0007_studenttestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequestmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Хүсэлт илгээсэн'), (2, 'Төлбөр хүлээгдэж байгаа'), (3, 'Бусад'), (3, 'Батлагдсан')], default=1, verbose_name='Төлөв'),
        ),
    ]
