# Generated by Django 3.2 on 2023-01-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0007_studentvideomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestmodel',
            name='course',
        ),
        migrations.AlterField(
            model_name='studenttestmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='surgalt.coursestudentmodel', verbose_name='Суралцагч'),
        ),
    ]
