# Generated by Django 3.2 on 2023-01-25 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0008_auto_20230123_1802'),
    ]

    operations = [
    ]
