# Generated by Django 3.2 on 2022-10-19 17:54

from django.db import migrations, models
import uo_core.utills


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0008_alter_courserequestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='Төлбөр (Нэг сар)'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=uo_core.utills.PathAndRename('course_pics/'), verbose_name='Зураг'),
        ),
    ]
