# Generated by Django 3.2 on 2023-01-25 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surgalt', '0011_alter_studentpointhistorymodel_commit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpointhistorymodel',
            name='commit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо'),
        ),
    ]
