# Generated by Django 4.0.2 on 2022-03-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('link_to_connect', models.CharField(max_length=256, unique=True, verbose_name='Холбогдох холбоос')),
                ('video_link', models.CharField(max_length=256, unique=True, verbose_name='Үзвэрийн холбоос(Youtube)')),
                ('loyalty_amount', models.FloatField(verbose_name='Урамшууллын үнэ')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Үзвэр урт')),
                ('watch_limit', models.IntegerField(blank=True, null=True, verbose_name='Үзвэр Үзэх хягаар')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Видео Үзвэр',
                'verbose_name_plural': 'Видео Үзвэрүүд',
                'db_table': 'sales_video',
            },
        ),
        migrations.CreateModel(
            name='VideoWatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_user', to=settings.AUTH_USER_MODEL, verbose_name='check time')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_video', to='sales.videomodel', verbose_name='check time')),
            ],
            options={
                'verbose_name': 'Үзвэр ба хэрэглэгч',
                'verbose_name_plural': 'Үзвэр ба хэрэглэгчид',
                'db_table': 'sales_video_watch',
            },
        ),
        migrations.CreateModel(
            name='VideoTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='check minute')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_check', to='sales.videomodel', verbose_name='check time')),
            ],
            options={
                'verbose_name': 'Шалгах Хугацаа',
                'verbose_name_plural': 'Шалгах Хугацаанууд',
                'db_table': 'sales_video_time',
            },
        ),
    ]
