# Generated by Django 3.2.12 on 2022-09-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellitemmodel',
            options={'verbose_name': 'Худалдах бараа', 'verbose_name_plural': '01 Худалдах бараанууд'},
        ),
    ]
