# Generated by Django 3.2.12 on 2022-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Нэр')),
                ('desc', models.CharField(max_length=256, verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Үзвэрийн ангилал',
                'verbose_name_plural': 'Үзвэрийн ангилалууд',
                'db_table': 'sales_video_cat',
            },
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='watch_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Үзвэр Үзэх хязгаар'),
        ),
    ]
