# Generated by Django 3.2.12 on 2022-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20220425_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategorymodel',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Тайлбар'),
        ),
    ]
