# Generated by Django 3.2 on 2024-02-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20230612_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'P1 Brands'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Захиалга', 'verbose_name_plural': 'B1 Захиалганууд'},
        ),
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'verbose_name': 'Бүтээгдэхүүн ангилал', 'verbose_name_plural': 'P1 Бүтээгдэхүүн ангилалууд'},
        ),
        migrations.AlterModelOptions(
            name='qpayinvoicemodel',
            options={'verbose_name': 'Qpay invoice', 'verbose_name_plural': 'B3 Qpay invoices'},
        ),
        migrations.AlterModelOptions(
            name='sellitemmodel',
            options={'verbose_name': 'Худалдах бараа', 'verbose_name_plural': 'P3 Худалдах бараанууд'},
        ),
        migrations.AlterModelOptions(
            name='sellitemtypemodel',
            options={'verbose_name': 'Бүтээгдэхүүн Загвар', 'verbose_name_plural': 'P2 Бүтээгдэхүүн Загварууд'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'B2 Transactions'},
        ),
    ]
