# Generated by Django 3.2.12 on 2022-04-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_videocategorymodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='host_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Эзэмшэгчийн нэр'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='Эзэмшэгчийн нэр'),
        ),
    ]
