# Generated by Django 3.2 on 2022-11-02 17:55

from django.db import migrations, models
import django.db.models.deletion
import uo_core.utills


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_address_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellitemmodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Үнэ'),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Нийт борлуулах тоо ширхэг'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Picture', max_length=100, null=True, verbose_name='Зураг гарчиг')),
                ('picture', models.ImageField(upload_to=uo_core.utills.PathAndRename('product_pics/'), verbose_name='Зураг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='эрэмбэ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='sales.sellitemmodel', verbose_name='Зурагнууд')),
            ],
            options={
                'verbose_name': 'Худалдах барааны зурагнууд',
                'db_table': 'sales_item_picture',
                'ordering': ['order'],
            },
        ),
    ]
