# Generated by Django 3.2 on 2022-11-19 10:36

from django.db import migrations, models
import django.db.models.deletion
import uo_core.utills


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20221102_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=uo_core.utills.PathAndRename('product_categories/'), verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_product', to='sales.sellitemmodel', verbose_name='Зурагнууд'),
        ),
    ]
