# Generated by Django 3.2.12 on 2022-04-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20220425_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_videos', to='sales.videocategorymodel', verbose_name='Төрөл'),
        ),
    ]
