# Generated by Django 3.2 on 2022-11-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20221119_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Сагс', 'verbose_name_plural': 'Сагснууд'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='sales_carts',
        ),
    ]
