# Generated by Django 3.2 on 2022-11-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20221122_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Сагсан дахь бараа', 'verbose_name_plural': 'Сагсан дахь бараанууд'},
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='sales_cart_item',
        ),
    ]
