# Generated by Django 3.2 on 2024-04-23 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_orderitem_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.sellitemtypemodel', verbose_name='Загвар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ширхэг үнэ'),
        ),
    ]
