# Generated by Django 3.2 on 2022-12-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20221122_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Захиалга', 'verbose_name_plural': 'Захиалганууд'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Захиалганд харгалзах бараа', 'verbose_name_plural': 'Захиалганд харгалзах бараанууд'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='sales_orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='sales_order_items',
        ),
    ]
