# Generated by Django 3.2 on 2023-01-21 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='QpayInvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref number')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment id')),
                ('qpay_qr_code', models.TextField(blank=True, null=True, verbose_name='QPAY QR code')),
                ('qpay_short_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='QPAY short ulr')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='мөнгөн дүн')),
                ('currency', models.CharField(blank=True, default='MNT', max_length=10, null=True, verbose_name='Мөнгөн тэмдэгт')),
                ('invoice_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='invoice name')),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='phone')),
                ('invoice_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='invoice discription')),
                ('qr_image', models.TextField(blank=True, null=True, verbose_name='qr image')),
                ('deep_link', models.TextField(blank=True, null=True, verbose_name='deeplinks')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Төлөгдсөн')),
                ('is_company', models.BooleanField(blank=True, default=False, null=True, verbose_name='Байгууллагаар')),
                ('company_register', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Байгууллагын регистер')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_qpay_user', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_qpay_user', to=settings.AUTH_USER_MODEL, verbose_name='Устгасан хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_qpay_user', to=settings.AUTH_USER_MODEL, verbose_name='Шинэчилсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Qpay invoice',
                'verbose_name_plural': 'Qpay invoices',
                'db_table': 'sales_qpay_invoice',
            },
        ),
    ]
