# Generated by Django 3.2 on 2023-01-24 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0013_qpayinvoicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref number')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment id')),
                ('transaction_type', models.IntegerField(blank=True, choices=[(1, 'ОРЛОГО'), (2, 'ЗАРЛАГА')], null=True, verbose_name='Гүйлгээний төрөл')),
                ('payment_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гүйлгээний утга')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Үнэ')),
                ('currency', models.CharField(blank=True, default='MNT', max_length=10, null=True, verbose_name='Мөнгөн тэмдэгт')),
                ('account_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Данс эзэмшигчийн ҮА чиглэл')),
                ('is_refunded', models.BooleanField(blank=True, default=0, null=True, verbose_name='Төлбөр буцаасан')),
                ('is_hand_charge', models.BooleanField(blank=True, default=0, null=True, verbose_name='Гараар нэмсэн')),
                ('charge_payment_called', models.IntegerField(blank=True, default=0, null=True, verbose_name='charged count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transaction_user', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_transaction_user', to=settings.AUTH_USER_MODEL, verbose_name='Устгасан хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_transaction_user', to=settings.AUTH_USER_MODEL, verbose_name='Шинэчилсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'gok_transaction',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransactionModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref number')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment id')),
                ('transaction_type', models.IntegerField(blank=True, choices=[(1, 'ОРЛОГО'), (2, 'ЗАРЛАГА')], null=True, verbose_name='Гүйлгээний төрөл')),
                ('payment_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гүйлгээний утга')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Үнэ')),
                ('currency', models.CharField(blank=True, default='MNT', max_length=10, null=True, verbose_name='Мөнгөн тэмдэгт')),
                ('account_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Данс эзэмшигчийн ҮА чиглэл')),
                ('is_refunded', models.BooleanField(blank=True, default=0, null=True, verbose_name='Төлбөр буцаасан')),
                ('is_hand_charge', models.BooleanField(blank=True, default=0, null=True, verbose_name='Гараар нэмсэн')),
                ('charge_payment_called', models.IntegerField(blank=True, default=0, null=True, verbose_name='charged count')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Устгасан хэрэглэгч')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Шинэчилсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'historical Transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
