# Generated by Django 3.2 on 2023-02-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20230206_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemattributes',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Бэлэн байгаа тоо ширхэг (-20 захиалах дээд хэмжээ, 0 байж болохгүй)'),
        ),
        migrations.AlterField(
            model_name='sellitemattributes',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.sellitemtypemodel', verbose_name='Загвар'),
        ),
    ]
