# Generated by Django 3.2 on 2023-02-08 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20230207_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellitemtypemodel',
            options={'verbose_name': 'Бүтээгдэхүүн Загвар', 'verbose_name_plural': 'Бүтээгдэхүүн Загварууд'},
        ),
        migrations.AlterField(
            model_name='sellitemattributes',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Үнэ'),
        ),
        migrations.AlterField(
            model_name='sellitemattributes',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Бэлэн байгаа тоо ширхэг (-20 захиалах дээд хэмжээ)'),
        ),
    ]
