# Generated by Django 3.2 on 2023-02-08 01:28

from django.db import migrations, models
import sales.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20230208_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemattributes',
            name='quantity',
            field=models.IntegerField(default=1, validators=[sales.models.validate_zero], verbose_name='Бэлэн байгаа тоо ширхэг (-20 захиалах дээд хэмжээ)'),
        ),
    ]
