# Generated by Django 3.2 on 2023-02-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20230208_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ширхэг үнэ'),
        ),
    ]
