# Generated by Django 3.2 on 2023-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_paid',
            field=models.FloatField(default=0, verbose_name='Төлөгдсөн дүн'),
        ),
    ]
